export const words = [
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
  "Vfx",
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
  "Vfx",
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
  "Vfx",
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
  "Vfx",
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
  "Vfx",
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
  "Vfx",
  "Animation",
  "Color Grading",
  "Video Production",
  "Optimisation",
  "Social Media",
  "Video Production",
  "Sfx",
];
